name: Release
on: push
jobs:
  test-defaults:
    runs-on: ubuntu-18.04
    name: Default version uses timestamps and package can be installed
    steps:
      - uses: actions/checkout@v1
      - id: xunit-viewer
        uses: ./  #use the current project relative to root
      - name: The generated report
        run: echo "The report is ${{ steps.xunit-viewer.outputs.report-file }}"    
      - name: Test
        run: |
            [ ${{ steps.xunit-viewer.outputs.report-file }} == "test-reports/index.html" ]
      - name: Attach the report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: ${{ steps.xunit-viewer.outputs.report-dir }}
